module.exports = {
    addScript: require('./lib/addScript.js').default,
    addStylesheet: require('./lib/addStylesheet.js').default,
    capitalize: require('./lib/capitalize.js').default,
    classy: require('./lib/classy.js').default,
    countryCodes: require('./lib/countryCodes.js').default,
    downloadFile: require('./lib/downloadFile.js').default,
    format: require('./lib/format.js').default,
    fullscreen: require('./lib/fullscreen.js').default,
    fuzzyMatch: require('./lib/fuzzyMatch.js').default,
    index: require('./lib/index.js').default,
    keymap: require('./lib/keymap.js').default,
    logger: require('./lib/logger.js').default,
    offView: require('./lib/offView.js').default,
    parseJSX: require('./lib/parseJSX.js').default,
    presets: require('./lib/presets.js').default,
    pureRender: require('./lib/pureRender.js').default,
    routeLoader: require('./lib/routeLoader.js').default,
    slugify: require('./lib/slugify.js').default,
    storage: require('./lib/storage.js').default,
    throttle: require('./lib/throttle.js').default,
    time: require('./lib/time.js').default,
    truncate: require('./lib/truncate.js').default,
    xhr: require('./lib/xhr.js').default,
};
